apiVersion: v1
kind: Pod
metadata:
  name: express-ssl
spec:
  containers:
  - name: express-api
    image: deboroy/simple-express-api
    ports:
    - name: http
      containerPort: 8080
  - name: envoy
    image: deboroy/envoy-ssl-proxy
    ports:
    - name: https
      containerPort: 8443
    - name: admin
      containerPort: 9901